<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array/>
	<key>name</key>
	<string>Serial Monitor</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>comment</key>
			<string>Matches the Timestamp</string>
			<key>match</key>
			<string>^\[(\d\d-){2}\d\d (\d\d:){2}\d\d\.\d{3}\]</string>
			<key>name</key>
			<string>comment.serial_monitor</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.serial_monitor</string>
	<key>uuid</key>
	<string>14525d9d-0fa1-455b-a9c2-547dbdd42150</string>
</dict>
</plist>
